# Generated by Django 4.1.5 on 2023-01-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlevel",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, default="kuojvjqc", max_length=8),
        ),
        migrations.AlterField(
            model_name="userlevel",
            name="title",
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
