# Generated by Django 4.1.5 on 2023-01-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='vcmzwqlc', max_length=8),
        ),
    ]
