# Generated by Django 4.1.5 on 2023-01-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_userlevel_description_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='gpknpylo', max_length=8),
        ),
    ]
