# Generated by Django 4.1.5 on 2023-01-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='data.usergroup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_level', to='data.userlevel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='rannslek', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_position', to='data.position'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='level',
            field=models.IntegerField(blank=True, default=1, unique=True),
        ),
    ]
