# Generated by Django 4.1.5 on 2023-01-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_user_company_alter_user_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='yasixjco', max_length=8),
        ),
    ]
