# Generated by Django 4.1.5 on 2023-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='display_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='positiongroup',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='vscunorw', max_length=8),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
