# Generated by Django 4.1.5 on 2023-01-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_position_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='ebarpvem', max_length=8),
        ),
    ]
