# Generated by Django 4.1.5 on 2023-01-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='qjhygrhm', max_length=8),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
