# Generated by Django 4.1.5 on 2023-01-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='cqrtlmrr', max_length=8),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='level',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
