# Generated by Django 4.1.5 on 2023-01-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_user_password_alter_userlevel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='display_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='imdxpaqm', max_length=8),
        ),
    ]
