# Generated by Django 4.1.5 on 2023-01-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_position_display_name_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='display_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='wcdudcay', max_length=8),
        ),
    ]
