# Generated by Django 4.1.5 on 2023-02-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pos_group',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='opmwwwtc', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='pos_group',
            field=models.ManyToManyField(related_name='product_position_group', to='data.positiongroup'),
        ),
    ]
