# Generated by Django 4.1.5 on 2023-02-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_remove_product_pos_group_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='tfuvcqjb', max_length=8),
        ),
    ]
