# Generated by Django 4.1.5 on 2023-02-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_remove_product_pos_group_product_pos_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='jscknebo', max_length=8),
        ),
    ]
