# Generated by Django 4.1.5 on 2023-02-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pos_groups',
            new_name='pos_group',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='adllzjsf', max_length=8),
        ),
    ]
