# Generated by Django 4.1.5 on 2023-02-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_rename_pos_groups_product_pos_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pos_group',
            field=models.ManyToManyField(blank=True, related_name='product_position_group', to='data.position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='ooieephf', max_length=8),
        ),
    ]
