# Generated by Django 4.1.5 on 2023-02-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_alter_product_pos_group_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pos_group',
            new_name='positions',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='bdvjjmfg', max_length=8),
        ),
    ]
