# Generated by Django 4.1.5 on 2023-02-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_rename_pos_group_product_positions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='positions',
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.ManyToManyField(blank=True, related_name='position', to='data.position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='mepbbxnf', max_length=8),
        ),
    ]
