# Generated by Django 4.1.5 on 2023-02-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_remove_product_positions_product_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_group',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='tvmvjkkk', max_length=8),
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
    ]
